name: 5.1_ubuntu20.04

on: [ workflow_dispatch ]

env:
  IMAGE_NAME: docker-avisynthplus
  #set tagname
  TAG_NAME: 5.1-ubuntu2004
  #set targetdir
  TARGET_DIR: 5.1/ubuntu20.04

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.TARGET_DIR }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

